name: Build LaTeX document
on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Release
      id: compile
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          apk add github-cli
          ./build.sh
          export GH_TOKEN=${{ github.token }}
          export GH_REPO=${{ github.repository }}
          RELEASE_TAG="$(date +'%d-%m-%Y')"
          gh release create "$RELEASE_TAG" --title "$RELEASE_TAG" || true
          gh release upload --clobber "$RELEASE_TAG" *.pdf
