name: Build LaTeX document
on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Release
      id: compile
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: ./build.sh; echo "files='$(find -name "*.pdf")'" >> $GITHUB_OUTPUT
    - name: Upload Built Ruby
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release upload --clobber "$(date +'%d-%m-%Y')" ${{ steps.compile.outputs.files }}
